'use strict';
const FETCH_REQUEST="FETCH_REQUEST";
const FETCH_RESPONSE_SUCCESS="FETCH_RESPONSE_SUCCESS";
const FETCH_RESPONSE_FAILURE="FETCH_RESPONSE_FAILURE";

export {
  FETCH_REQUEST,
  FETCH_RESPONSE_SUCCESS,
  FETCH_RESPONSE_FAILURE,
}
