const LOGIN_USER_REQUEST='LOGIN_USER_REQUEST';
const LOGIN_USER_FAILURE='LOGIN_USER_FAILURE';
const LOGIN_USER_SUCCESS='LOGIN_USER_SUCCESS';
const LOGOUT_USER='LOGOUT_USER';
const DEFAULT_ERROR_MESSAGE='DEFAULT_ERROR_MESSAGE';
export {
  LOGIN_USER_REQUEST,
  LOGIN_USER_SUCCESS,
  LOGIN_USER_FAILURE,
  LOGOUT_USER,
  DEFAULT_ERROR_MESSAGE
};
