'use strict';
const FETCH_REQUEST="FETCH_REQUEST";
const FETCH_RESPONSE_SUCCESS="FETCH_RESPONSE_SUCCESS";
const FETCH_RESPONSE_FAILURE="FETCH_RESPONSE_FAILURE";
const NO_USER_ON_THIS_PAGE="NO_USER_ON_THIS_PAGE";
// const SEARCH_SUCCESSFULL="SEARCH_SUCCESSFULL";
// const SEARching

export {
  FETCH_REQUEST,
  FETCH_RESPONSE_SUCCESS,
  FETCH_RESPONSE_FAILURE,
  NO_USER_ON_THIS_PAGE

}
